### PR TITLE
WIP: Use method_missing to access options

### PR DESCRIPTION
**Pull request by tylerklose**
## What does this PR do?
Uses `method_missing` to access options. For example, let's say I have a CLI command that takes an arbitrary number of string arguments:

```ruby
def bitbucket
  option '--bitbucket'
end

def branch
  option '--branch'
end

def github
  option '--github'
end

def gitlab
  option '--gitlab'
end

def hash
  option '--hash'
end

...

```

Rather than having to define each and everyone of these arguments, we can use `method_missing` to fetch the value for us. For example, we can easily get `:mod_name` by simply calling `mod_name` or `--github`'s value by calling `github`

## Do you have any concerns about this body of work? Anything you'd like to highlight or open for discussion? Anything to be aware of before merging / deploying?
I'm not sure if any of this is desirable. I'm not sure if we want to limit this to only fetching options prefixed with `--` rather than all of them.

There are limitations to this. You could not use `repo_name` to get the value for `--repo-name`

For example: `command 'install mod :mod_name'`
Should we be able to just call `mod_name` or should we only be able to get the value of `--github` or `--gitlab`?

## Where should the review start?
`lib/gotta/cli/command.rb`

## Recommendation/Steps for how to test this
TODO

## Link to the related issue(s)
None

### CODE REVIEW

**Comment by parruda** [comment]
I have some concerns about merging this PR that I'd like to put up for discussion.

### The use of :params
The idea of forming commands with `:params` is so that values can be obtained without having to be passed as command line arguments. When I built this feature, those values were meant to be passed before any option as a constructor for a nice command line experience. For example: `gotta new :type project :name` would allow for `gotta new api project my-project`, parsing to `{type: 'api', name: 'my-project'}`.

Options are meant to be command line arguments, like `-f` or `--github URL`. If we follow the structure that was initially created, you would never have `:params` into options.

That's why you would put parameters `:params` into the string you pass to the `command` method, but never to the options.

### About CLI arguments
I think it is important that pass command line arguments with `-` or `--`, as it conforms with the current standard in all CLI tools out there.

### About using method_missing
It looks like a good idea at first, but it will hurt us in the future when we add a very important missing feature to `gotta-cli`: auto-generated help.
```
$ gotta get help
$ gotta ?
$ gotta -h
$ gotta help
```
The above commands should return a help that is auto generated with the description that is passed to the method `command`. For example, when declaring a command, it would look like:
```
command 'new :type project :name', description: 'Creates a new gotta project...'`

**Comment by parruda** [comment]
I updated my comment and removed the first part that was not relevant.

**Comment by parruda** [comment]
You actually made me realize that there's no interface for accessing the params like `options`

For example, from the project cli new command, the value for the project name is fetched like:

```ruby
def name
  @args['name']
end
```

We should have something to help declaring those params like `option`. For example:

```ruby
def name
  param :name
end
```

**Comment by tylerklose** [comment]
Will need to revisit this...

**Pull request closed without merging**
